jobs:
  testing:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Clone repository
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Execute tests
      run: './gradlew test

        '
name: Unit tests
on:
  repository_dispatch:
    types: trigger-ga___run_tests.yml
