jobs:
  trigger-termux-library-builds:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Set vars
      run: echo "TERMUX_LIB_VERSION=${GITHUB_REF/refs\/tags\/v/}" >> $GITHUB_ENV
    - continue-on-error: true
      name: Echo release
      run: echo "Triggering termux library builds on jitpack for '$TERMUX_LIB_VERSION'
        release after waiting for 3 mins"
    - continue-on-error: true
      name: Trigger termux library builds on jitpack
      run: 'sleep 180 # It will take some time for the new tag to be detected by Jitpack

        curl --max-time 600 --no-progress-meter "https://jitpack.io/com/termux/termux-app/terminal-emulator/$TERMUX_LIB_VERSION/terminal-emulator-$TERMUX_LIB_VERSION.pom"

        curl --max-time 600 --no-progress-meter "https://jitpack.io/com/termux/termux-app/terminal-view/$TERMUX_LIB_VERSION/terminal-view-$TERMUX_LIB_VERSION.pom"

        curl --max-time 600 --no-progress-meter "https://jitpack.io/com/termux/termux-app/termux-shared/$TERMUX_LIB_VERSION/termux-shared-$TERMUX_LIB_VERSION.pom"

        '
name: Trigger Termux Library Builds on Jitpack
on:
  repository_dispatch:
    types: trigger-ga___trigger_library_builds_on_jitpack.yml
